version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: challenger00t

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api
#    ports:
#      - 3004:3004

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq/
    environment:
       - RABBITMQ_DEFAULT_USER=admin
       - RABBITMQ_DEFAULT_PASS=root123
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8181


volumes:
  data:
    driver: local